#############################################################################
# Makefile for building: watering_analizer
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Feb 23 10:32:12 2016
# Project:  watering_analizer.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile watering_analizer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		com/qextserialport.cpp \
		com/qextserialenumerator_unix.cpp \
		com/posix_qextserialport.cpp \
		globalstatedialog.cpp \
		waterstorages.cpp \
		visualconfig.cpp \
		connectdlg.cpp moc_qextserialenumerator.cpp \
		moc_qextserialport.cpp \
		moc_globalstatedialog.cpp \
		moc_waterstorages.cpp \
		moc_visualconfig.cpp \
		moc_connectdlg.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		qextserialport.o \
		qextserialenumerator_unix.o \
		posix_qextserialport.o \
		globalstatedialog.o \
		waterstorages.o \
		visualconfig.o \
		connectdlg.o \
		moc_qextserialenumerator.o \
		moc_qextserialport.o \
		moc_globalstatedialog.o \
		moc_waterstorages.o \
		moc_visualconfig.o \
		moc_connectdlg.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		watering_analizer.pro
QMAKE_TARGET  = watering_analizer
DESTDIR       = 
TARGET        = watering_analizer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_globalstatedialog.h ui_waterstorages.h ui_visualconfig.h ui_connectdlg.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: watering_analizer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile watering_analizer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile watering_analizer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/watering_analizer1.0.0 || $(MKDIR) .tmp/watering_analizer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/watering_analizer1.0.0/ && $(COPY_FILE) --parents com/qextserialenumerator.h com/qextserialport_global.h com/qextserialport.h data_structs.h globalstatedialog.h waterstorages.h visualconfig.h connectdlg.h .tmp/watering_analizer1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/watering_analizer1.0.0/ && $(COPY_FILE) --parents main.cpp com/qextserialport.cpp com/qextserialenumerator_unix.cpp com/posix_qextserialport.cpp globalstatedialog.cpp waterstorages.cpp visualconfig.cpp connectdlg.cpp .tmp/watering_analizer1.0.0/ && $(COPY_FILE) --parents globalstatedialog.ui waterstorages.ui visualconfig.ui connectdlg.ui .tmp/watering_analizer1.0.0/ && (cd `dirname .tmp/watering_analizer1.0.0` && $(TAR) watering_analizer1.0.0.tar watering_analizer1.0.0 && $(COMPRESS) watering_analizer1.0.0.tar) && $(MOVE) `dirname .tmp/watering_analizer1.0.0`/watering_analizer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/watering_analizer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qextserialenumerator.cpp moc_qextserialport.cpp moc_globalstatedialog.cpp moc_waterstorages.cpp moc_visualconfig.cpp moc_connectdlg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qextserialenumerator.cpp moc_qextserialport.cpp moc_globalstatedialog.cpp moc_waterstorages.cpp moc_visualconfig.cpp moc_connectdlg.cpp
moc_qextserialenumerator.cpp: com/qextserialport_global.h \
		com/qextserialenumerator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) com/qextserialenumerator.h -o moc_qextserialenumerator.cpp

moc_qextserialport.cpp: com/qextserialport_global.h \
		com/qextserialport.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) com/qextserialport.h -o moc_qextserialport.cpp

moc_globalstatedialog.cpp: com/qextserialport.h \
		com/qextserialport_global.h \
		globalstatedialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) globalstatedialog.h -o moc_globalstatedialog.cpp

moc_waterstorages.cpp: com/qextserialport.h \
		com/qextserialport_global.h \
		waterstorages.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) waterstorages.h -o moc_waterstorages.cpp

moc_visualconfig.cpp: com/qextserialport.h \
		com/qextserialport_global.h \
		data_structs.h \
		visualconfig.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) visualconfig.h -o moc_visualconfig.cpp

moc_connectdlg.cpp: com/qextserialport.h \
		com/qextserialport_global.h \
		connectdlg.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) connectdlg.h -o moc_connectdlg.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		water_hose.png \
		res/open.png \
		res/apply.png \
		res/lift_up.png \
		res/1444255829_database-import.png \
		res/1444255815_hammer_screwdriver.png \
		res/find.png \
		res/1443055450_water--arrow.png \
		res/search.png \
		res/save.png \
		res/transmit.png \
		res/1443644018_revert.png \
		res/singledrop.png \
		res/connect.png \
		res/water.png \
		res/lift_down.png \
		res/1443055443_water--minus.png \
		res/moveto.png \
		res/disconnect.png \
		res/1443055440_water--exclamation.png \
		res/download.png \
		res/1443055668_arrow_circle_double.png \
		res/1443055446_water--pencil.png \
		res/1443976919_compile.png \
		res/1443055436_water--plus.png
	/usr/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_globalstatedialog.h ui_waterstorages.h ui_visualconfig.h ui_connectdlg.h
compiler_uic_clean:
	-$(DEL_FILE) ui_globalstatedialog.h ui_waterstorages.h ui_visualconfig.h ui_connectdlg.h
ui_globalstatedialog.h: globalstatedialog.ui
	/usr/bin/uic-qt4 globalstatedialog.ui -o ui_globalstatedialog.h

ui_waterstorages.h: waterstorages.ui
	/usr/bin/uic-qt4 waterstorages.ui -o ui_waterstorages.h

ui_visualconfig.h: visualconfig.ui
	/usr/bin/uic-qt4 visualconfig.ui -o ui_visualconfig.h

ui_connectdlg.h: connectdlg.ui
	/usr/bin/uic-qt4 connectdlg.ui -o ui_connectdlg.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp visualconfig.h \
		com/qextserialport.h \
		com/qextserialport_global.h \
		data_structs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qextserialport.o: com/qextserialport.cpp com/qextserialport.h \
		com/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o com/qextserialport.cpp

qextserialenumerator_unix.o: com/qextserialenumerator_unix.cpp com/qextserialenumerator.h \
		com/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialenumerator_unix.o com/qextserialenumerator_unix.cpp

posix_qextserialport.o: com/posix_qextserialport.cpp com/qextserialport.h \
		com/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posix_qextserialport.o com/posix_qextserialport.cpp

globalstatedialog.o: globalstatedialog.cpp globalstatedialog.h \
		com/qextserialport.h \
		com/qextserialport_global.h \
		ui_globalstatedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globalstatedialog.o globalstatedialog.cpp

waterstorages.o: waterstorages.cpp waterstorages.h \
		com/qextserialport.h \
		com/qextserialport_global.h \
		ui_waterstorages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waterstorages.o waterstorages.cpp

visualconfig.o: visualconfig.cpp visualconfig.h \
		com/qextserialport.h \
		com/qextserialport_global.h \
		data_structs.h \
		ui_visualconfig.h \
		connectdlg.h \
		globalstatedialog.h \
		waterstorages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o visualconfig.o visualconfig.cpp

connectdlg.o: connectdlg.cpp connectdlg.h \
		com/qextserialport.h \
		com/qextserialport_global.h \
		ui_connectdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectdlg.o connectdlg.cpp

moc_qextserialenumerator.o: moc_qextserialenumerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialenumerator.o moc_qextserialenumerator.cpp

moc_qextserialport.o: moc_qextserialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialport.o moc_qextserialport.cpp

moc_globalstatedialog.o: moc_globalstatedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_globalstatedialog.o moc_globalstatedialog.cpp

moc_waterstorages.o: moc_waterstorages.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_waterstorages.o moc_waterstorages.cpp

moc_visualconfig.o: moc_visualconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_visualconfig.o moc_visualconfig.cpp

moc_connectdlg.o: moc_connectdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectdlg.o moc_connectdlg.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

